/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ule_config.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ac47b330fd3a9b573b11dbe5a0f9f6a2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ule/ule_config.h>
// pydoc.h is automatically generated in the build directory
#include <ule_config_pydoc.h>

void bind_ule_config(py::module& m)
{


    py::enum_<::gr::ule::ule_ping_reply_t>(m,"ule_ping_reply_t")
        .value("PING_REPLY_OFF", ::gr::ule::PING_REPLY_OFF) // 0
        .value("PING_REPLY_ON", ::gr::ule::PING_REPLY_ON) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::ule::ule_ping_reply_t>();
    py::enum_<::gr::ule::ule_ipaddr_spoof_t>(m,"ule_ipaddr_spoof_t")
        .value("IPADDR_SPOOF_OFF", ::gr::ule::IPADDR_SPOOF_OFF) // 0
        .value("IPADDR_SPOOF_ON", ::gr::ule::IPADDR_SPOOF_ON) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::ule::ule_ipaddr_spoof_t>();



}








