/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ule_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c5434d700bca208c4de4603f1e81a8ad)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ule/ule_source.h>
// pydoc.h is automatically generated in the build directory
#include <ule_source_pydoc.h>

void bind_ule_source(py::module& m)
{

    using ule_source    = ::gr::ule::ule_source;


    py::class_<ule_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ule_source>>(m, "ule_source", D(ule_source))

        .def(py::init(&ule_source::make),
           py::arg("mac_address"),
           py::arg("filename"),
           py::arg("frequency"),
           py::arg("call_sign"),
           py::arg("ping_reply"),
           py::arg("ipaddr_spoof"),
           py::arg("src_address"),
           py::arg("dst_address"),
           D(ule_source,make)
        )
        



        ;




}








